name: Docker

on:
  push:
    branches:
      - master

jobs:
  Docker:
    name: Build image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          repository: mipirakas/githubactions
          tags: latest
          tag_with_ref: true